updateChecker: true # Disable the update checker
metrics: true # Disable the bStats metrics

# Disable or enable drops/exp when player kills mob with Insta-Kill
drop-items: true
drop-exp: true

# Disable or enable Insta-Kill to other players.
insta-kill-players: false

activeInstaKill:
  - Example