name: InstaKillMobs
version: ${version}
api-version: 1.13
author: TonimatasDEV
description: Insta kill mobs in Game Mode set in config file.

main: net.tonimatasdev.instakillmobs.InstaKillMobs

commands:
  instakillmobs:
    description: Primary command.

permissions:
  instakillmobs.*:
    description: All permissions of InstaKillMobs.
    children:
      instakillmobs.other: true
      instakillmobs.me: true

  instakillmobs.other:
    description: Insta-kill mobs permission to other.

  instakillmobs.me:
    description: Insta-kill mobs permission to me.